spring:
  flyway:
    enabled: false
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        use_sql_comments: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://43.202.45.134:3306/every_garden?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: QUFehwls123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: # TODO - add email
    password: # TODO - add credentials
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
