async:
  image:
    corePoolSize: 10       # 스레드 풀의 기본 스레드 수
    maxPoolSize: 13        # 스레드 풀의 최대 스레드 수
    queCapacity: 10000     # 작업 큐의 용량
    keepAliveSeconds: 60    # 최대 스레드 수가 기본 스레드 수를 초과할 때, 초과한 스레드가 유휴 상태로 있을 수 있는 최대 시간(초)
    threadName: "image-executor"  # 생성되는 스레드의 이름 접두사
