spring:
  datasource:
    hikari:
      jdbc-url: ${JDBC_URL}
      username: ${DB_USERNAME}
      password: ${DB_SECRET}
  flyway:
    url: ${JDBC_URL}
    user: ${DB_USERNAME}
    password: ${DB_SECRET}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_SECRET}

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
  jwt:
    token-secret: ${JWT_TOKEN_SECRET}
    access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    authority-key: ${AUTHORITY_KEY}
    refresh-token-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
    access-token-header: ${ACCESS_TOKEN_HEADER}

api:
  mafra:
    url: http://211.237.50.150:7080/openapi/${PUBLIC_GARDEN_API_SECRET_KEY}/json/Grid_20171122000000000552_1/1/1000
  weather:
    secret: ${PUBLIC_WEATHER_API_SECRET_KEY}
  reverseGeo:
    id: ${NAVER_OPEN_API_ID}
    secret: ${NAVER_OPEN_API_SECRET}
  slack:
    bot: ${SLACK_WEBHOOK_URL}
cloud:
  ncp:
    region: ${NCP_REGION}
    accessKey: ${NCP_ACCESS_KEY}
    secretKey: ${NCP_SECRET_KEY}
    bucket: ${NCP_BUCKET_NAME}
    baseDirectory: ${NCP_BASE_DIRECTORY}
